source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

use_frameworks!

target 'TAOverlayView_Example' do
  pod 'TAOverlayView', :path => '../'
end


target 'TAOverlayView_Tests' do
  pod 'TAOverlayView', :path => '../'
  
  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
